- hosts: databases
  remote_user: root
  vars:
    tablename: foo
    tableowner: someuser

  tasks:
    # Rename table
    - name: Rename table {{ tablename }} to bar
      postgresql_table:
        table: {{ tablename }}
        rename: bar

    # Set user privilege
    - name: Set owner to someuser
      postgresql_table:
        name: {{ tablename }}
        owner: someuser

    # Truncate table
    - name: Truncate table {{ tablename }}
      postgresql_table:
        name: {{ tablename }}
        truncate: yes

