---
- name: Install java and net-tools
  hosts: nexus_server
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3500
    - name: Install openjdk-11-jre-headless
      apt: name=openjdk-11-jre-headless state=present
    - name: Install net-tools
      apt: name=net-tools 

- name: Download and unpack Nexus Installer
  hosts: nexus_server
  tasks:
    - name: Check nexus folder stats exist or not
      stat:
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result}}
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}}
    - name: Untar nexus Installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists  
    - name: Find nexus folder
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - debug: msg={{find_result}}
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: Create nexus user to own nexus folders
  hosts: nexus_server
  tasks:
    - name: Ensure group nexus exist
      group:
        name: nexus
        state: present
    - name: Create nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner for nexus folder
      file:
        path: /opt/nexus
        state: directory
        user: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner for sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        user: nexus
        group: nexus
        recurse: yes    

- name: Start nexus with nexus user
  hosts: nexus_server
  become: yes
  become_user: nexus
  tasks:
    - name: Set run_as_user nexus
#      blockinfile:
#        path: /opt/nexus/bin/nexus.rc
#        block: |
#          run_as_user="nexus"
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regex: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus Start

- name: Verify nexus running
  hosts: nexus_server
  tasks:
    - name: Check with ps
      shell: ps aux | grep nexus
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: Wait one minute
      pause:
        minute: 1
    - name: Check with netstat
      shell: netstat -lpnt
      register: app_status
    - debug: msg={{app_status.stdout_lines}}      